/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rubenrdc.sistemgest.GUI;

/**
 *
 * @author Ruben
 */
public class SelectorPractice extends javax.swing.JFrame {

    Practice2NumerosPrimos windows2;
    Practice1IndiceMasaCorporal windows1;
    Practice3ListArrayList windows3;
    Practice4ListClass windows4;
    Practice5ListBD windows5;

    /**
     * Creates new form SelectorPractice
     */
    public SelectorPractice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnP1 = new javax.swing.JButton();
        btnP2 = new javax.swing.JButton();
        btnP3 = new javax.swing.JButton();
        btnP4 = new javax.swing.JButton();
        btnP5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Practices");

        btnP1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnP1.setText("Practice #1");
        btnP1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnP1MouseClicked(evt);
            }
        });

        btnP2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnP2.setText("Practice #2");
        btnP2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnP2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnP2MouseClicked(evt);
            }
        });

        btnP3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnP3.setText("Practice #3");
        btnP3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnP3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnP3MouseClicked(evt);
            }
        });

        btnP4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnP4.setText("Practice #4");
        btnP4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnP4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnP4MouseClicked(evt);
            }
        });

        btnP5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnP5.setText("Practice #5");
        btnP5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnP5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnP5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnP2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(btnP3, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(btnP4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(btnP5, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnP1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnP2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnP3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnP4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnP5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ruben Ruiz Diaz Centurion - version 0.5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnP2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnP2MouseClicked

        if (windows2 == null) {
            windows2 = null;
            windows2 = new Practice2NumerosPrimos();
            windows2.setVisible(true);
            windows2.setLocationRelativeTo(null);
            windows2.setResizable(false);

        } else if (windows2.isShowing()) {
            System.out.println("if (windows2!=null) ");
            windows2.toFront();
        } else {
            windows2.setVisible(true);
            windows2.setLocationRelativeTo(null);
            windows2.setResizable(false);
        }
    }//GEN-LAST:event_btnP2MouseClicked

    private void btnP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnP1MouseClicked

        if (windows1 == null) {
            windows1 = null;
            windows1 = new Practice1IndiceMasaCorporal();
            windows1.setVisible(true);
            windows1.setLocationRelativeTo(null);
            windows1.setResizable(false);

        } else if (windows1.isShowing()) {
            System.out.println("if (windows1!=null) ");
            windows1.toFront();
        } else {
            windows1.setVisible(true);
            windows1.setLocationRelativeTo(null);
            windows1.setResizable(false);
        }
    }//GEN-LAST:event_btnP1MouseClicked

    private void btnP3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnP3MouseClicked
        if (windows3 == null) {
            windows3 = null;
            windows3 = new Practice3ListArrayList();
            windows3.setVisible(true);
            windows3.setLocationRelativeTo(null);
            windows3.setResizable(false);

        } else if (windows3.isShowing()) {
            System.out.println("if (windows1!=null) ");
            windows3.toFront();
        } else {
            windows3.setVisible(true);
            windows3.setLocationRelativeTo(null);
            windows3.setResizable(false);
        }
    }//GEN-LAST:event_btnP3MouseClicked

    private void btnP4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnP4MouseClicked
        if (windows4 == null) {
            windows4 = null;
            windows4 = new Practice4ListClass();
            windows4.setVisible(true);
            windows4.setLocationRelativeTo(null);
            windows4.setResizable(false);

        } else if (windows4.isShowing()) {
            System.out.println("if (windows1!=null) ");
            windows4.toFront();
        } else {
            windows4.setVisible(true);
            windows4.setLocationRelativeTo(null);
            windows4.setResizable(false);
        }
    }//GEN-LAST:event_btnP4MouseClicked

    private void btnP5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnP5MouseClicked
        if (windows5 == null) {
            windows5 = null;
            windows5 = new Practice5ListBD();
            windows5.setVisible(true);
            windows5.setLocationRelativeTo(null);
            windows5.setResizable(false);

        } else if (windows5.isShowing()) {
            System.out.println("if (windows1!=null) ");
            windows5.toFront();
        } else {
            windows5.setVisible(true);
            windows5.setLocationRelativeTo(null);
            windows5.setResizable(false);
        }
    }//GEN-LAST:event_btnP5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnP1;
    private javax.swing.JButton btnP2;
    private javax.swing.JButton btnP3;
    private javax.swing.JButton btnP4;
    private javax.swing.JButton btnP5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
